# Generated by Django 4.2.6 on 2024-01-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageFeature_CNN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.TextField()),
                ("feature", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ImageFeature_Eff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.TextField(unique=True)),
                ("feature", models.BinaryField()),
            ],
        ),
    ]
