# Generated by Django 4.2.6 on 2024-01-10 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_image", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImageFeature",
            new_name="ImageFeature_CNN",
        ),
    ]
