# Generated by Django 4.2.6 on 2024-01-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_image", "0002_rename_imagefeature_imagefeature_cnn"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageFeature_Eff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.TextField()),
                ("feature", models.BinaryField(default=b"")),
            ],
        ),
    ]
