# Generated by Django 4.2.6 on 2024-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_image", "0003_imagefeature_eff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefeature_eff",
            name="image_path",
            field=models.TextField(unique=True),
        ),
    ]
