# Generated by Django 4.2.6 on 2024-01-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_image", "0005_alter_imagefeature_eff_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefeature_eff",
            name="feature",
            field=models.BinaryField(),
        ),
    ]
